apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: subscription-admin
rules:
- apiGroups:
  - apps.app1.io
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - apps.api.app1.io
  resources:
  - '*'
  verbs:
  - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: subscription-admin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: subscription-admin
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: bob
