---
apiVersion: v1
kind: Namespace
metadata:
  name: multins
---
apiVersion: kubevirt.io/v1alpha3
kind: KubeVirt
metadata:
  name: kubevirt
  namespace: kubevirt
spec:
  imagePullPolicy: IfNotPresent
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-configmap-3
  namespace: multins
data:
  path: resource1111
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-configmap-1
  namespace: default
data:
  path: resource2222
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-configmap-2
  namespace: default
data:
  path: resource3333222
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-configmap-5
  namespace: default
data:
  path: resource2222
