apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: subscription-admin
rules:
- apiGroups:
  - apps.newapp.io
  resources:
  - '*'
  verbs:
  - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: subscription-admin
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: rokej