apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: cloud-provider-spoke
  namespace: provider
  labels:
    app: cloud
spec:
  clusterConditions:
    - type: ManagedClusterConditionAvailable
      status: "True"
  clusterSelector:
    matchLabels:
      environment: dev