apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: cloud-local
  namespace: provider
  annotations:
    apps.open-cluster-management.io/github-path: cloud-provider/nginx
    apps.open-cluster-management.io/github-branch: master
  labels:
    app: cloud
spec:
  channel: demo/gitops
  placement:
    placementRef:
      name: cloud-provider-local
      kind: PlacementRule
  packageOverrides:
  - packageName: cloud-provider/nginx/kustomization
    packageOverrides:
    - value:
        namespace: provider
        resources:
        - service.yaml
        - deployment-local.yaml