apiVersion: hive.openshift.io/v1
kind: ClusterDeployment
metadata:
  name: rjung-spoke13
  namespace: rjung-spoke13
  labels:
    cloud: 'AWS'
    region: 'us-east-2'
    vendor: 'OpenShift'
spec:
  baseDomain: dev06.red-chesterfield.com
  clusterName: rjung-spoke13
  controlPlaneConfig:
    servingCertificates: {}
  installed: false
  platform:
    aws:
      credentialsSecretRef:
        name: rjung-spoke13-aws-creds
      region: us-east-2
  provisioning:
    installConfigSecretRef:
      name: rjung-spoke13-install-config
    sshPrivateKeySecretRef:
      name: rjung-spoke13-ssh-private-key
    imageSetRef:
       #quay.io/openshift-release-dev/ocp-release:4.6.1-x86_64
      name: img4.6.1-x86-64
  pullSecretRef:
    name: rjung-spoke13-pull-secret
---
apiVersion: cluster.open-cluster-management.io/v1
kind: ManagedCluster
metadata:
  labels:
    cloud: Amazon
    region: us-east-2
    name: rjung-spoke13
    vendor: OpenShift
    environment: 'dev'
  name: rjung-spoke13
spec:
  hubAcceptsClient: true
---
apiVersion: hive.openshift.io/v1
kind: MachinePool
metadata:
  name: rjung-spoke13-worker
  namespace: rjung-spoke13
spec:
  clusterDeploymentRef:
    name: rjung-spoke13
  name: worker
  platform:
    aws:
      rootVolume:
        iops: 100
        size: 100
        type: gp2
      type: m5.xlarge
  replicas: 3
---
apiVersion: v1
kind: Secret
metadata:
  name: rjung-spoke13-pull-secret
  namespace: rjung-spoke13
data:
  .dockerconfigjson: eyJhdXRocyI6eyJjbG91ZC5vcGVuc2hpZnQuY29tIjp7ImF1dGgiOiJiM0JsYm5Ob2FXWjBMWEpsYkdWaGMyVXRaR1YySzNKdmEyVnFkVzVuY21neGVtbzJhSGx0YTI0d2NHRXlNREpsT0d3M1kycDRlSFJsYm1vNlNEQkJVbGN4VjBRNVFWRllRak15V2xsUFJqZzJWalJVV2xRM1VsWXhUMXBOVEVKVFJGQkRWakZZVTBvMVdqWkRWamxIU1RRNU0wOHhVVVpYVFRJelFnPT0iLCJlbWFpbCI6InJqdW5nQHJlZGhhdC5jb20ifSwicXVheS5pbyI6eyJhdXRoIjoiYjNCbGJuTm9hV1owTFhKbGJHVmhjMlV0WkdWMkszSnZhMlZxZFc1bmNtZ3hlbW8yYUhsdGEyNHdjR0V5TURKbE9HdzNZMnA0ZUhSbGJtbzZTREJCVWxjeFYwUTVRVkZZUWpNeVdsbFBSamcyVmpSVVdsUTNVbFl4VDFwTlRFSlRSRkJEVmpGWVUwbzFXalpEVmpsSFNUUTVNMDh4VVVaWFRUSXpRZz09IiwiZW1haWwiOiJyanVuZ0ByZWRoYXQuY29tIn0sInJlZ2lzdHJ5LmNvbm5lY3QucmVkaGF0LmNvbSI6eyJhdXRoIjoiTlRNeU56WXhOVFI4ZFdoakxURmFTalpJV1cxclRqQlFZVEl3TW1VNGJEZGpTbGg0ZEVWdWFqcGxlVXBvWWtkamFVOXBTbE5WZWxWNFRXbEtPUzVsZVVwNlpGZEphVTlwU21oTmJVbDZXa1JrYlUxNlFYaE9WRlV3V2xkSmQxbFVhM2haYlVwdFRXcFJNRTU2VFRWWlYxcHBUMU5LT1M1U1ozUlNUMlZUZUV4MVNXMWlYMkpGTFhWUVl6SnJTa2RJT1hwbldtOVFNWE5qZURobFJFdFlWMFJYTjBJM1NFcFdhMDlmVUROb2FtcFFlR3BzZVRObFNYa3lNMkp4ZWpWV2IzbDVjVVZCV21sS1FYTkRVRkE0Wm1vMlRtUTBUazVWZDFweFNuazRlRU5UV2twWE1reFFSRVZPT1c5QlMzaHlhSEY1WW5KV1RURm5UM2t5TmtGUlJuWm5SSGR3TVZwSlVtWnpVRjgzTWtkSFpWVjRObVJmTlZad2VFTTBNVTQ1UVUxVFVYbFdiWE5qY1ZsU2VXa3dOVTA0WDNSTlRHbEVRblp5UW10UGNHZG1TelZFUm1GdVQxTllNM1pSZW1SSWNYcHlUVFJpWVdKdlZGVXhjVlJ6ZGtablZXWndSekJGWVZKaU5tMXJTamxKTVMwMGVGcHFZVVZaU1VWNFR6UXdaV2RpV0docVIzZGtWVnBvV2psa1NqVlhkekpuWkdwU1NrSkxWREYyTTNsVk1qUjVVRVp6YVdKRGVsOVpORVEwUzFkRWREbDNOR1JrVFMxNk9VeHJXR2RCVlRoQllWWmhiM0l3YTFVemVHRk5iRnBaWW1od01sWnlMVzFRU3pkRWVtaGphMVl5U1ZKdWRHRnFXWHBLTTNkNmJqTjZZWGRvT0VKb2FYcGFMVEZUZDJ4TVIyZ3lhSFpYUkd0M1lVZE5WRlZWZURJM2VXZHVSamxFYUVKS1RsQlhNRFZCT0dWWFpFa3pla3h0V0ZGYWJTMW5RM1JWVUhsaldsZHJYMGN5TWxwbU9ETmxOSEppZEVwWk5qVmxiWFZHZVRKRVgyWjNPSEJCVmpWdmQxazJOVFJEUVRSb1VGSjROM0JvYVdaSlIxQTBNREpETVRSaldUQlhYMXBMYVhoMlVVaHJTREYxV1RkUVRHd3paMVl5ZEZaR0xWWkhVRUkyTWxCeWFGOXdkRWgxVEdONlFtaFBiSFJvUzFoTGVXSmhSVnAzUVhOTWFUQm9jMU5vUjNsTlkxQXdWbDh0YW1wR1pXeHljbXd3WjJscmMxZHpRVzlmYVhwcFRHSjFYMEZKUVRWdFNqWkNiR2RDYTNsU2NGWXlPVWgwYlVWb1ZrVkZPVVpLU0hkblpVTlZNbTA0T0hSalUyRlRkbE4xYlZsWVJsRjNNVzkxVnkxdE1EbEJNa1pwVVE9PSIsImVtYWlsIjoicmp1bmdAcmVkaGF0LmNvbSJ9LCJyZWdpc3RyeS5yZWRoYXQuaW8iOnsiYXV0aCI6Ik5UTXlOell4TlRSOGRXaGpMVEZhU2paSVdXMXJUakJRWVRJd01tVTRiRGRqU2xoNGRFVnVhanBsZVVwb1lrZGphVTlwU2xOVmVsVjRUV2xLT1M1bGVVcDZaRmRKYVU5cFNtaE5iVWw2V2tSa2JVMTZRWGhPVkZVd1dsZEpkMWxVYTNoWmJVcHRUV3BSTUU1NlRUVlpWMXBwVDFOS09TNVNaM1JTVDJWVGVFeDFTVzFpWDJKRkxYVlFZekpyU2tkSU9YcG5XbTlRTVhOamVEaGxSRXRZVjBSWE4wSTNTRXBXYTA5ZlVETm9hbXBRZUdwc2VUTmxTWGt5TTJKeGVqVldiM2w1Y1VWQldtbEtRWE5EVUZBNFptbzJUbVEwVGs1VmQxcHhTbms0ZUVOVFdrcFhNa3hRUkVWT09XOUJTM2h5YUhGNVluSldUVEZuVDNreU5rRlJSblpuUkhkd01WcEpVbVp6VUY4M01rZEhaVlY0Tm1SZk5WWndlRU0wTVU0NVFVMVRVWGxXYlhOamNWbFNlV2t3TlUwNFgzUk5UR2xFUW5aeVFtdFBjR2RtU3pWRVJtRnVUMU5ZTTNaUmVtUkljWHB5VFRSaVlXSnZWRlV4Y1ZSemRrWm5WV1p3UnpCRllWSmlObTFyU2psSk1TMDBlRnBxWVVWWlNVVjRUelF3WldkaVdHaHFSM2RrVlZwb1dqbGtTalZYZHpKblpHcFNTa0pMVkRGMk0zbFZNalI1VUVaemFXSkRlbDlaTkVRMFMxZEVkRGwzTkdSa1RTMTZPVXhyV0dkQlZUaEJZVlpoYjNJd2ExVXplR0ZOYkZwWlltaHdNbFp5TFcxUVN6ZEVlbWhqYTFZeVNWSnVkR0ZxV1hwS00zZDZiak42WVhkb09FSm9hWHBhTFRGVGQyeE1SMmd5YUhaWFJHdDNZVWROVkZWVmVESTNlV2R1UmpsRWFFSktUbEJYTURWQk9HVlhaRWt6ZWt4dFdGRmFiUzFuUTNSVlVIbGpXbGRyWDBjeU1scG1PRE5sTkhKaWRFcFpOalZsYlhWR2VUSkVYMlozT0hCQlZqVnZkMWsyTlRSRFFUUm9VRko0TjNCb2FXWkpSMUEwTURKRE1UUmpXVEJYWDFwTGFYaDJVVWhyU0RGMVdUZFFUR3d6WjFZeWRGWkdMVlpIVUVJMk1sQnlhRjl3ZEVoMVRHTjZRbWhQYkhSb1MxaExlV0poUlZwM1FYTk1hVEJvYzFOb1IzbE5ZMUF3Vmw4dGFtcEdaV3h5Y213d1oybHJjMWR6UVc5ZmFYcHBUR0oxWDBGSlFUVnRTalpDYkdkQ2EzbFNjRll5T1VoMGJVVm9Wa1ZGT1VaS1NIZG5aVU5WTW0wNE9IUmpVMkZUZGxOMWJWbFlSbEYzTVc5MVZ5MXRNRGxCTWtacFVRPT0iLCJlbWFpbCI6InJqdW5nQHJlZGhhdC5jb20ifX19
type: kubernetes.io/dockerconfigjson
---
apiVersion: v1
kind: Secret
metadata:
  name: rjung-spoke13-install-config
  namespace: rjung-spoke13
type: Opaque
data:
  # Base64 encoding of install-config yaml
  install-config.yaml: YXBpVmVyc2lvbjogdjEKbWV0YWRhdGE6CiAgbmFtZTogcmp1bmctc3Bva2UxMQpiYXNlRG9tYWluOiBkZXYwNi5yZWQtY2hlc3RlcmZpZWxkLmNvbQpjb250cm9sUGxhbmU6CiAgaHlwZXJ0aHJlYWRpbmc6IEVuYWJsZWQKICBuYW1lOiBtYXN0ZXIKICByZXBsaWNhczogMwogIHBsYXRmb3JtOgogICAgYXdzOgogICAgICByb290Vm9sdW1lOgogICAgICAgIGlvcHM6IDQwMDAKICAgICAgICBzaXplOiAxMDAKICAgICAgICB0eXBlOiBpbzEKICAgICAgdHlwZTogbTUueGxhcmdlCmNvbXB1dGU6Ci0gaHlwZXJ0aHJlYWRpbmc6IEVuYWJsZWQKICBuYW1lOiB3b3JrZXIKICByZXBsaWNhczogMwogIHBsYXRmb3JtOgogICAgYXdzOgogICAgICByb290Vm9sdW1lOgogICAgICAgIGlvcHM6IDIwMDAKICAgICAgICBzaXplOiAxMDAKICAgICAgICB0eXBlOiBpbzEKICAgICAgdHlwZTogbTUueGxhcmdlCm5ldHdvcmtpbmc6CiAgY2x1c3Rlck5ldHdvcms6CiAgLSBjaWRyOiAxMC4xMjguMC4wLzE0CiAgICBob3N0UHJlZml4OiAyMwogIG1hY2hpbmVDSURSOiAxMC4wLjAuMC8xNgogIG5ldHdvcmtUeXBlOiBPcGVuU2hpZnRTRE4KICBzZXJ2aWNlTmV0d29yazoKICAtIDE3Mi4zMC4wLjAvMTYKcGxhdGZvcm06CiAgYXdzOgogICAgcmVnaW9uOiB1cy1lYXN0LTIKcHVsbFNlY3JldDogIiIgIyBza2lwLCBoaXZlIHdpbGwgaW5qZWN0IGJhc2VkIG9uIGl0J3Mgc2VjcmV0cwpzc2hLZXk6IHwtCiAgICBzc2gtcnNhIEFBQUFCM056YUMxeWMyRUFBQUFEQVFBQkFBQUJnUUNrSjR1NW1Ya1RSTDN1WmFXV1ZTM0Rpb1VjTGp3T3JzL0Q3aXFwK0g0c0p1WmdyZ2tYa0ZZUmxjSDFFbEc4cDBNMWs4SGFITHkwck4wazdkazZDT1MrQ3B1QnppWjAwQ1hhdlY5MC8yclo4R2dFZGZkUjh5UUs3d0lxYi9rT2RoNHJRTGdpR2Znd0VXaS95d3dZdWZHYisyQTlzMzU4bldjdVN2ckYrZWMvL3F5REVhb3E3QVNLeEFPRnZ0anRxUHc1NDQwYUh3d092Nk5yQlc1T1RpemR3MU51VlVjODJUVGhsMW83cWlZamVIUzZ6Smk1VVFTbGJzMHpLc3ZLeElBNHVBSUQrSG93N1dNdDhyRW05eFB6MGo2cVJWSWRlSE1pUW1neDhRS3NCSlFUN3d3aGtYeXFnYUhpa3lJOG9qSTZYM1U0ajJ0UXZEUTNBZi9wQ3RQOFJYWURnck1Na1RnbGxiWlZ3L25XY0lDSGV0WFJEUlQxL3VQUGNzTjJZLzcxeTMyWUdFN1VtaHFaUTc5MXZMTzZPNHNvL3FNSTVPYkxvZnpwSC90U2Z6OUNYRWlHb0lKOWIrSWZwOHpQMW12eCs2Zyt6NDNzV3E2Y3FJU0xxdjROZkFkUWZXQ05oQVJGWm5lL0tueGF4OUliK0lrL29Wdno3OWFyazYxZUJ4OD0gcmp1bmdATWFjQm9vay1Qcm8K
---
apiVersion: v1
kind: Secret
metadata:
  name: rjung-spoke13-ssh-private-key
  namespace: rjung-spoke13
data:
  ssh-privatekey: LS0tLS1CRUdJTiBPUEVOU1NIIFBSSVZBVEUgS0VZLS0tLS0KYjNCbGJuTnphQzFyWlhrdGRqRUFBQUFBQkc1dmJtVUFBQUFFYm05dVpRQUFBQUFBQUFBQkFBQUJsd0FBQUFkemMyZ3RjbgpOaEFBQUFBd0VBQVFBQUFZRUFwQ2VMdVpsNUUwUzk3bVdsbGxVdHc0cUZIQzQ4RHE3UHcrNHFxZmgrTENibVlLNEpGNUJXCkVaWEI5UkpSdktkRE5aUEIyaHk4dEt6ZEpPM1pPZ2prdmdxYmdjNG1kTkFsMnIxZmRQOXEyZkJvQkhYM1VmTWtDdThDS20KLzVEblllSzBDNElobjRNQkZvdjhzTUdMbnhtL3RnUGJOK2ZKMW5Ma3I2eGZublAvNnNneEdxS3V3RWlzUURoYjdZN2FqOApPZU9OR2g4TURyK2phd1Z1VGs0czNjTlRibFZIUE5rMDRaZGFPNm9tSTNoMHVzeVl1VkVFcFc3Tk15ckx5c1NBT0xnQ0EvCmg2TU8xakxmS3hKdmNUODlJK3FrVlNIWGh6SWtKb01mRUNyQVNVRSs4TUlaRjhxb0doNHBNaVBLSXlPbDkxT0k5clVMdzAKTndILzZRclQvRVYyQTRLekRKRTRKWlcyVmNQNTFuQ0FoM3JWMFEwVTlmN2p6M0xEZG1QKzljdDltQmhPMUpvYW1VTy9kYgp5enVqdUxLUDZqQ09UbXk2SDg2Ui83VW44L1FseElocUNDZlcvaUg2Zk16OVpyOGZ1b1BzK043RnF1bktpRWk2citEWHdIClVIMWdqWVFFUldaM3Z5cDhXc2ZTRy9pSlA2RmI4Ky9XcTVPdFhnY2ZBQUFGaUlncVJNdUlLa1RMQUFBQUIzTnphQzF5YzIKRUFBQUdCQUtRbmk3bVplUk5FdmU1bHBaWlZMY09LaFJ3dVBBNnV6OFB1S3FuNGZpd201bUN1Q1JlUVZoR1Z3ZlVTVWJ5bgpReldUd2RvY3ZMU3MzU1R0MlRvSTVMNEttNEhPSm5UUUpkcTlYM1QvYXRud2FBUjE5MUh6SkFydkFpcHYrUTUySGl0QXVDCklaK0RBUmFML0xEQmk1OFp2N1lEMnpmbnlkWnk1SytzWDU1ei8rcklNUnFpcnNCSXJFQTRXKzJPMm8vRG5qalJvZkRBNi8KbzJzRmJrNU9MTjNEVTI1VlJ6elpOT0dYV2p1cUppTjRkTHJNbUxsUkJLVnV6VE1xeThyRWdEaTRBZ1A0ZWpEdFl5M3lzUwpiM0UvUFNQcXBGVWgxNGN5SkNhREh4QXF3RWxCUHZEQ0dSZktxQm9lS1RJanlpTWpwZmRUaVBhMUM4TkRjQi8ra0swL3hGCmRnT0Nzd3lST0NXVnRsWEQrZFp3Z0lkNjFkRU5GUFgrNDg5eXczWmovdlhMZlpnWVR0U2FHcGxEdjNXOHM3bzdpeWorb3cKams1c3VoL09rZisxSi9QMEpjU0lhZ2duMXY0aCtuek0vV2EvSDdxRDdQamV4YXJweW9oSXVxL2cxOEIxQjlZSTJFQkVWbQpkNzhxZkZySDBodjRpVCtoVy9QdjFxdVRyVjRISHdBQUFBTUJBQUVBQUFHQWNDSVRjRlZHUDhOVmV1UTBtTnpXeGh4NWtTCmFFSUFPS0tXMG45N09uZk1HVjNiVUV3UFAzMTB0Vmt2TlFvbTRmbXhtejhpcHZQWHhZRkVIbGdaOVJvZi9jK202NEZsT1oKaURLVVluZVhwZ2h6QlprUHVRcytNN25RNE94Y1ZXU2FkekZlbHV6bWZPOW5mcHhWUnc2OTNLOTZycXRPWEJHcHloV3QrRQo4ZGlMbVBYbmxTcEw5VTJ2WEs4akhNUFl5UnYzbVJpYVpydGlkeW1raTdjUUkxNDhicDF4U3A5UWJxK0s5TEZEYkdsclJTCkNNaDZDeDBzNzFVaEZ6TEV3MTQyb0hRQzl6N1BjaU9pZVh4amV4RUZHSnkxbytvVmFmeUJHdURJbkdsRTEzeHB0U0V3clkKcVNxbWVrSVJRRU9nWjlSVjlhZjd0RGdtc29kRDZ6Nmw2WjlnUWJuOU9xQ1pMWnlkWFQrRmxwbUg5MGdGaFp0UzVEN25HVApvbGdQckl6K1c4UUhjc0V5M3JNazRuRDQvcUhuNndxSzdBZHNhcGhxOCtNL1RiMkpHNjl5dUlBNTVWSWgrRTIzZ2s2Z2dlCllwQVZJMnNFWEJkWDNGZ0QvVk5oRDdocUlGQ3lySVFYRXdoNW4zcnA0dmRkOVJIZm5yWnRIK2s2QWs5bUxRTTlBQkFBQUEKd0RQcFI0SENoTUpJTGRWby96bnhCUHlTYkVEUnQ4YVZtbFBMRXgwdWNGZVNWU1VtcXJDbVpaN3V5RzVoV3VCblVyV25ZQQpDRnRIazdaM3M0Ym9XNy9maU5BSlZEUDBCbHJtRDhxeEhocWNCZXozTHRieTFwV0pRR0NYZzAwdTBxS1Y5d25MUmU1b29vCjU0emNYNDFVMG9ybEdzSk41d0pBU2NuNTFiZVNHSjFVdWI4Y1JSRER2dHIxRnhVZnlkTU95U2xuWU5seEpidTZHSGxFMHkKRUdMM1BYVFVDMzRjOTZIUUhndEgrR1V6WTA3SVEyQmFzaFpFbTBVTjBvT1NDUUFRQUFBTUVBenJ0NlhJZEZ1WXZxQUNGMwpJdE9FZXdxdGpvSUZ4OGk4QmZ2eGtya3ZGSTVtQzJtTFFJNTIvckRVMlRxNlM3T0RVZ3VPMHVwS09TNnE5WGo5NCtnOE1OCkpad3h3MTZDMnBOMHRjd0dSMVRKYmdOYlFBMUd0K2FwMzJXZlMvbGNRNUNSZi8xenVJVXJYUkRKSkZOaUVyNEVZRExiWDMKWjU3TmNTZDkzZUNqeHVUNkZGdkhTbm5aOXJ0Y01tZCt3cU5yemdTWmxyMDJreGwxcTlDdElnTGFmUG4veXRiWkdNM2hvZQpBUElHSVVvR2NoK0sxMDl4ZUlPcW40L0swcWUrVkJBQUFBd1FETFJtLzcrUEdVTHdpb2JQZDFHN0RuU3p5UWdyM2ErMmlvCmJ1SThIcEVwcVdqYTVTeEJHNHFWVnpiQTdWUHFTSlI5VEpUS0tmVzh0UC9WNWJ4dXk5VDZUanFhNUZQOFZSVkRTbHpMMDcKUXlKYXpEaFlvUlEyT0NlT01aQkRtbVJTRzhBMEZyaW1ZU3lLSzVabnFHYy9mRUUvYnRGc0lJMFRyRkZFZUFZTEsyU0FhOApRaGVlaDVtay9jK1VTTFRMMVoxSXhlRVVEZ2YxaCtKbUc1dHpVZG5lU3JORnNuN0pHem1Oc0gvK1hFVTJMUXVsczFRa1VsCm5TV1h6djBSQmk5RjhBQUFBUmNtcDFibWRBVFdGalFtOXZheTFRY204QkFnPT0KLS0tLS1FTkQgT1BFTlNTSCBQUklWQVRFIEtFWS0tLS0t
type: Opaque
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: rjung-spoke13-aws-creds
  namespace: rjung-spoke13
data:
  aws_access_key_id: QUtJQTRKWllQRkVPNjMyTDdCQkI=
  aws_secret_access_key: dmxXc1VRU3p6Ulk5OW1hdTZKYWg3U0d0UUtRaEZRL2FRZ2YzczdaQQ==
---
apiVersion: agent.open-cluster-management.io/v1
kind: KlusterletAddonConfig
metadata:
  name: rjung-spoke13
  namespace: rjung-spoke13
spec:
  clusterName: rjung-spoke13
  clusterNamespace: rjung-spoke13
  clusterLabels:
    cloud: Amazon
    vendor: OpenShift
  applicationManager:
    enabled: true
  policyController:
    enabled: true
  searchCollector:
    enabled: true
  certPolicyController:
    enabled: true
  iamPolicyController:
    enabled: true
  version: 2.1.0
