---
apiVersion: v1
kind: Namespace
metadata:
  name: demo-ns-2
---
apiVersion: apps.open-cluster-management.io/v1
kind: Channel
metadata:
  name: somechannel-2
  namespace: demo-ns-2
spec:
  type: GitHub
  pathname: https://github.com/rokej/rokejtest.git
---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: demo-subscription-22222
  namespace: demo-ns-2
  annotations:
    apps.open-cluster-management.io/github-path: resources2
    apps.open-cluster-management.io/cluster-admin: "true"
spec:
  channel: demo-ns-2/somechannel-2
  placement:
    local: true
