apiVersion: v1
appVersion: "1.0"
description: test chart 1
name: chart1
version: 1.1.1
category: "Development"
verified: "QA"
tillerVersion: ">=2.9.1"
kubeVersion: ">=1.10.0"
keywords:
  - deploy
  - amd64
