
---
apiVersion: v1
kind: Namespace
metadata:
  name: newns
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-configmap-4
  namespace: newns
  annotations:
    test: 123
data:
  path: newresource333
