# kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# namespace to deploy all Resources to
namespace: open-cluster-management-policies

generatorOptions:
  disableNameSuffixHash: true

patches:
- target:
    version: v1
    kind: ConfigMap
    name: test-configmap-3
  patch: |-
    - op: replace
      path: /data/path
      value: newpath

# list of Resource Config to be Applied
resources:
  - policy-auth-provider.yaml