apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: placement-umbrella-openshift
  namespace: umbrella-policy
spec:
  clusterConditions:
  - status: "True"
    type: ManagedClusterConditionAvailable
  clusterSelector:
    matchExpressions:
      - {key: vendor, operator: In, values: ["OpenShift"]}
