---
apiVersion: v1
kind: ImageStream
metadata:
  name: default
  namespace: default
spec:
  lookupPolicy:
    local: true
  tags:
    - name: 'latest'
      from:
        kind: DockerImage
        name: 'https://quay.io/repository/open-cluster-management/multicluster-operators-subscription:community-latest'